// Bundles src/main.ts into main.js, the file Obsidian loads.
//
//   node esbuild.config.mjs             watch mode, inline source maps
//   node esbuild.config.mjs production  one minified build, then exit
//
// OBSIDIAN_PLUGIN_DIR=<vault>/.obsidian/plugins/obsidian-insights writes
// main.js, manifest.json and styles.css straight into a vault, so a watch
// build plus the Hot Reload community plugin is the whole dev loop.

import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, mkdirSync } from "fs";
import { join } from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
The source is plugin/src/ in https://github.com/slappycat2/obsidian-insights
*/
`;

const prod = process.argv[2] === "production";
const outDir = process.env.OBSIDIAN_PLUGIN_DIR || ".";

if (outDir !== ".") {
	mkdirSync(outDir, { recursive: true });
	for (const name of ["manifest.json", "styles.css"]) {
		copyFileSync(name, join(outDir, name));
	}
}

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	minify: prod,
	outfile: join(outDir, "main.js"),
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
