"""Filesystem anchors for v_chk.

Every runtime path is derived from the location of *this file* rather than from
the current working directory. That means v_chk behaves identically whether it
is launched from the repository root, from vault_check/, from src/, from a
PyCharm run configuration, or from a pytest run -- none of which agree on what
the working directory should be.

Layout::

    vault_check/                 <- APP_DIR
    |-- CONFIG.yaml              <- CONFIG_FILE (generated by the setup screen)
    |-- data/                    <- DATA_DIR
    |   |-- batch_files/         <- BATCH_DIR    (v_chk_NNNN.yaml handoff files)
    |   +-- workbooks/           <- WORKBOOK_DIR (v_chk_NNNN.xlsx output)
    |-- img/                     <- IMG_DIR
    |-- logs/                    <- LOG_DIR
    +-- src/                     <- SRC_DIR
        +-- logging_configs/     <- LOGGING_CONFIG_DIR
"""

from pathlib import Path

SRC_DIR = Path(__file__).resolve().parent
APP_DIR = SRC_DIR.parent
PROJECT_ROOT = APP_DIR.parent

LOGGING_CONFIG_DIR = SRC_DIR / "logging_configs"

CONFIG_FILE = APP_DIR / "CONFIG.yaml"
DATA_DIR = APP_DIR / "data"
BATCH_DIR = DATA_DIR / "batch_files"
WORKBOOK_DIR = DATA_DIR / "workbooks"
LOG_DIR = APP_DIR / "logs"
IMG_DIR = APP_DIR / "img"

# Image assets. Note the capitalisation: these must match the filenames on disk
# exactly, because macOS and Linux filesystems are case-sensitive.
LOGO_SPLASH = IMG_DIR / "SwenLogo200.png"
LOGO_SETUP = IMG_DIR / "SwenLogo300.png"
ICON_WINDOW = IMG_DIR / "swenlogo.ico"
BANNER = IMG_DIR / "v_chkBanner2.png"
AREA51 = IMG_DIR / "area51.png"

#: Directories v_chk creates on demand rather than requiring in the repository.
RUNTIME_DIRS = (DATA_DIR, BATCH_DIR, WORKBOOK_DIR, LOG_DIR)


def ensure_runtime_dirs() -> None:
    """Create the generated-output directories if they do not already exist."""
    for directory in RUNTIME_DIRS:
        directory.mkdir(parents=True, exist_ok=True)
